Improve Error Message for Invalid Password
Healthlane-Technologies/zelthy3 pull request #177
Opened 2024-03-29 17:49 UTC by AjaySDwivedi1

2024-04-02 06:46 UTC, shahharsh176 requested changes

2024-04-02 06:46 UTC, shahharsh176 commented on backend/src/zelthy/apps/shared/platformauth/models.py
> -                    else:
@AjaySDwivedi1 We don't need to remove the `else` block here, we can just update the `message` string

2024-04-08 12:18 UTC, shahharsh176 approved these changes

2024-04-08 12:40 UTC, kc-diabeat approved these changes

2024-04-08 12:40 UTC, merged